steps:
  - name: gcr.io/cloud-builders/docker
    args:
      - build
      - --build-arg
      - NEXT_PUBLIC_API_URL=https://lexguard-712213214076.us-central1.run.app
      - -t
      - gcr.io/gen-lang-client-0271684603/lexguard-frontend:latest
      - .
images:
  - gcr.io/gen-lang-client-0271684603/lexguard-frontend:latest
